# Generated by Django 3.2.4 on 2022-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageRead',
            field=models.BooleanField(default=False),
        ),
    ]
